### ISSUE TITLE
vrp_firescript wont working

### ISSUE THREAD

**Issue by tomas2k18** [Wick89/WK-FireScript#1]
I started in server.cfg already added the permission "wk.fire" and still it's not doing nothing ...

**Comment by Wick89** [comment]
do you add wk.fire in your groups.lua??

**Comment by tomas2k18** [comment]
Yes i did Sr. 

I added wk.fire in my group " Bombeiros " = Firefighter in english and nothing happens . I waited 1 , 2 hours

**Comment by Wick89** [comment]
ty to made a test go in server.lua and line 17 set to local timerSpawn = math.random(500, 600)

**Comment by Wick89** [comment]
have made a full updated at it work fint on my server

**Comment by tomas2k18** [comment]
I will try that

**Comment by tomas2k18** [comment]
Yep didn't work i dont know whats the problem

**Comment by Wick89** [comment]
Work fint on My server, only readd wk.Fire in server.lua and add it to your group.lua see it Work and ty to made a test go in server.lua and line 17 set to local timerSpawn = math.random(500, 600)

**Comment by Wick89** [comment]
sry my bad, can see some vrp server cant run it have same problem in 
local source = vRP.getUserSource({fired})
                TriggerClientEvent('WK:CreateBlip', -1,
